/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ESCRITORIO;

import BBDD.Conexion;
import DAO_IMP.ServicioDaoImp;
import DTO.ServicioDto;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel
 */
public class agregarServicios extends javax.swing.JFrame {

    /**
     * Creates new form agregarServicios
     */
    public agregarServicios() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_noms = new javax.swing.JTextField();
        t_precio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        t_descripcion = new javax.swing.JTextField();
        chkHab = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agregar servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Nombre Servicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 93, -1, -1));

        jLabel3.setText("Precio                       $");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 139, -1, -1));

        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 191, -1, -1));

        t_noms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nomsActionPerformed(evt);
            }
        });
        getContentPane().add(t_noms, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 87, 157, -1));

        t_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_precioActionPerformed(evt);
            }
        });
        getContentPane().add(t_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 133, 124, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 353, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 353, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 353, -1, -1));

        t_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(t_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 185, 318, -1));

        chkHab.setText("Habilitado");
        chkHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabActionPerformed(evt);
            }
        });
        getContentPane().add(chkHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mfOAU8I.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        desbloquear();
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_nomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nomsActionPerformed
        t_noms.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_nomsActionPerformed

    private void t_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_precioActionPerformed
        t_precio.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_precioActionPerformed

    private void t_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_descripcionActionPerformed
        t_descripcion.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_descripcionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        
      
        

ServicioDto dto= new ServicioDto();
        ServicioDaoImp dao= new ServicioDaoImp();
        dto.setNombre(t_noms.getText());
        dto.setPrecio(Integer.parseInt(t_precio.getText()));
        dto.setDescripcion(t_descripcion.getText());
        if(chkHab.isSelected()){
            dto.setHabilitado(true);
        }else{
            dto.setHabilitado(false);
        }
        
        if(dao.agregar(dto)){
            JOptionPane.showMessageDialog(null,"Error al agregar");
        }else{
            JOptionPane.showMessageDialog(null, "Se agrego correctamente");
        }


        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chkHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabActionPerformed
    chkHab.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_chkHabActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpiar() {
        t_noms.setText("");
        t_precio.setText("");
        t_descripcion.setText("");
        chkHab.setSelected(false);
    }

    public void bloquear() {
        t_noms.setEnabled(false);
        chkHab.setEnabled(false);
        t_precio.setEnabled(false);
        t_descripcion.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnNuevo.setEnabled(true);
    }

    public void desbloquear() {
        t_noms.setEnabled(true);
        chkHab.setEnabled(true);
        t_precio.setEnabled(true);
        t_descripcion.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnNuevo.setEnabled(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkHab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t_descripcion;
    private javax.swing.JTextField t_noms;
    private javax.swing.JTextField t_precio;
    // End of variables declaration//GEN-END:variables
}
