/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ESCRITORIO;

import BBDD.Conexion;
import DAO_IMP.TrabajadorDaoImp;
import DTO.TrabajadorDto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel
 */
public class registroTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form registroTrabajador
     */
    public registroTrabajador() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_rut = new javax.swing.JTextField();
        t_nom = new javax.swing.JTextField();
        t_dir = new javax.swing.JTextField();
        t_tel = new javax.swing.JTextField();
        t_tip = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_esp = new javax.swing.JTextField();
        t_corr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        t_contra = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        tNacimiento = new com.toedter.calendar.JDateChooser();
        chkHab = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese datos del Trabajador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, -1, -1));

        jLabel2.setText("Rut");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 72, -1, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, -1, -1));

        jLabel4.setText("Dirección");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 158, -1, -1));

        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 204, -1, -1));

        jLabel6.setText("Tipo Trabajador");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        t_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rutActionPerformed(evt);
            }
        });
        jPanel1.add(t_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 113, -1));

        t_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nomActionPerformed(evt);
            }
        });
        jPanel1.add(t_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 113, -1));

        t_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_dirActionPerformed(evt);
            }
        });
        jPanel1.add(t_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 113, -1));

        t_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_telActionPerformed(evt);
            }
        });
        jPanel1.add(t_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 113, -1));

        t_tip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tipActionPerformed(evt);
            }
        });
        jPanel1.add(t_tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 113, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setText("Especialidad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel10.setText("Fecha nacimiento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        t_esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_espActionPerformed(evt);
            }
        });
        jPanel1.add(t_esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 113, -1));

        t_corr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_corrActionPerformed(evt);
            }
        });
        jPanel1.add(t_corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 113, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 46, 417, 10));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel11.setText("Contraseña");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 72, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        t_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_contraActionPerformed(evt);
            }
        });
        jPanel1.add(t_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, -1));

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, -1));
        jPanel1.add(tNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        chkHab.setText("Habilitado");
        chkHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabActionPerformed(evt);
            }
        });
        jPanel1.add(chkHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mfOAU8I.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rutActionPerformed
        t_rut.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_rutActionPerformed

    private void t_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nomActionPerformed
        t_nom.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_nomActionPerformed

    private void t_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_dirActionPerformed
        t_dir.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_dirActionPerformed

    private void t_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_telActionPerformed
        t_tel.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_telActionPerformed

    private void t_tipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tipActionPerformed
        t_tip.transferFocus();      // TODO add your handling code here:
    }//GEN-LAST:event_t_tipActionPerformed

    private void t_espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_espActionPerformed
        t_esp.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_espActionPerformed

    private void t_corrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_corrActionPerformed
        t_corr.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_corrActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        desbloquear();
        limpiar();// TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        TrabajadorDto tr = new TrabajadorDto();
        TrabajadorDaoImp dao = new TrabajadorDaoImp();
        tr.setRut(t_rut.getText());
        tr.setNombre(t_nom.getText());
        tr.setCorreo(t_corr.getText());
        tr.setDireccion(t_dir.getText());
        tr.setTelefono(t_tel.getText());
        tr.setEspecialidad(t_esp.getText());
        SimpleDateFormat formato= new SimpleDateFormat("dd/mm/yy");
        Calendar cal= Calendar.getInstance();
        Date a=cal.getTime();
        tr.setFechaNacimiento(a));
        tr.setTipo(t_tip.getText());
        tr.setContrasenia(t_contra.getText());
        tr.setSexo(txtSexo.getText());
        if (chkHab.isSelected()) {
            tr.setHabilitado(true);
        } else {
            tr.setHabilitado(false);
        }

        if (dao.agregar(tr)) {
            JOptionPane.showMessageDialog(null, "Error al agregar al trabajador");
        } else {
            JOptionPane.showMessageDialog(null, "Exito al agregar el Trabajador");

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void t_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_contraActionPerformed
        t_contra.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_t_contraActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        txtSexo.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void chkHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabActionPerformed
        chkHab.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_chkHabActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpiar() {
        t_rut.setText("");
        t_nom.setText("");
        t_dir.setText("");
        t_corr.setText("");
        t_esp.setText("");
        t_tel.setText("");
        t_tip.setText("");
        t_contra.setText("");
        txtSexo.setText("");
        chkHab.setSelected(false);
        tNacimiento.setCalendar(null);

    }

    public void bloquear() {
        t_rut.setEnabled(false);
        t_nom.setEnabled(false);
        t_dir.setEnabled(false);
        t_corr.setEnabled(false);
        t_esp.setEnabled(false);
        t_tel.setEnabled(false);
        txtSexo.setEnabled(false);
        t_tip.setEnabled(false);
        t_contra.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnRegistrar.setEnabled(false);
        tNacimiento.setEnabled(false);
        chkHab.setEnabled(false);
    }

    public void desbloquear() {
        t_rut.setEnabled(true);
        t_nom.setEnabled(true);
        txtSexo.setEnabled(true);
        t_dir.setEnabled(true);
        t_corr.setEnabled(true);
        t_esp.setEnabled(true);
        t_tel.setEnabled(true);
        t_tip.setEnabled(true);
        t_contra.setEnabled(true);
        btnRegistrar.setEnabled(true);
        btnNuevo.setEnabled(true);
        tNacimiento.setEnabled(true);
        chkHab.setEnabled(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkHab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser tNacimiento;
    private javax.swing.JTextField t_contra;
    private javax.swing.JTextField t_corr;
    private javax.swing.JTextField t_dir;
    private javax.swing.JTextField t_esp;
    private javax.swing.JTextField t_nom;
    private javax.swing.JTextField t_rut;
    private javax.swing.JTextField t_tel;
    private javax.swing.JTextField t_tip;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
